apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: system
type: Opaque
stringData:
    config.yaml: |
        ipam:
          infoblox:
            host: "1.2.3.4"
            wapi_version: "2.x.x"
            port: 443
            username: "user"
            password: "pass"
        kubeconfigBackup:
          repo: https://example.com/gitops/kubeconfigs.git
          gitlabToken: "mytoken"
